ServiceHost/Areas/Administration/Pages/Account/Accounts/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contract.Account;
using AccountManagement.Application.Contract.Roles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Account.Accounts
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public AccountSearchModel SearchModel { get; set; } 
        public List<AccountViewModel> Accounts { get; set; }
        public SelectList Roles;
        private readonly IRoleApplication _roleApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }


        public void OnGet(AccountSearchModel searchModel)
        {
           Accounts = _accountApplication.Search(searchModel);
           Roles = new SelectList(_roleApplication.List(), "Id", "Name");
        }

        public IActionResult OnGetCreate()
        {
            var command = new RegisterAccount()
            {
                Roles = _roleApplication.List()
            };
            return Partial("./Create",command );
        }

        public JsonResult OnPostCreate(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetails(id);
            account.Roles = _roleApplication.List();
            return Partial("./Edit",account);
        }
        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }
        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword() {Id = id};
            return Partial("./ChangePassword", command);
        }
        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Account/Roles/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contract.Roles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        public CreateRole Command;
        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Account/Roles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contract.Roles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    permissions.AddRange(value);
                    foreach (var permission in value)
                    {
                        var group = new SelectListGroup()
                        {
                            Name = key
                        };
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };
                        if (Command.MapedPermissions.Any(x => x.Code == permission.Code))
                        {
                            item.Selected = true;
                        }

                        Permissions.Add(item);
                    }
                }
            }
        }
        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Account/Roles/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contract.Account;
using AccountManagement.Application.Contract.Roles;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Account.Roles
{
    public class IndexModel : PageModel
    {
        public List<RoleViewModel> Roles { get; set; }
        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }


        public void OnGet(AccountSearchModel searchModel)
        {
            Roles = _roleApplication.List();
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contract.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {

        [TempData] public string LoginMessage { get; set; }

        [TempData] public string RegisterMessage { get; set; }

        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostLogin(Login command)
        {
            var result = _accountApplication.Login(command);
            if (result.IsSucceeded)
                return RedirectToPage("/Index");
            LoginMessage = result.Message;
            return RedirectToPage("/Account");
        }

        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            if (result.IsSucceeded)
                return RedirectToPage("/Account");

            RegisterMessage = result.Message;
            return RedirectToPage("/Account");

        }
    }
}

ServiceHost/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nancy.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages
{
    public class CartModel : PageModel
    {
        private readonly IProductQuery _productQuery;
        public List<CartItem> CartItems;
        public const string CookieName = "cart-items";
        public CartModel(IProductQuery productQuery)
        {
            CartItems = new List<CartItem>();
            _productQuery = productQuery;
        }

        public void OnGet()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
                foreach (var item in cartItems)
                    item.CalculateTotalItemPrice();

            CartItems = _productQuery.CheckInventoryStatus(cartItems);
        }

        public IActionResult OnGetRemoveFromCart(long id)
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            Response.Cookies.Delete(CookieName);
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            var itemToRemove = cartItems.FirstOrDefault(x => x.Id == id);
            cartItems.Remove(itemToRemove);
            var options = new CookieOptions
            {
                SameSite = SameSiteMode.Lax,
                Expires = DateTime.Now.AddDays(2)
            };
            Response.Cookies.Append(CookieName, serializer.Serialize(cartItems), options);
            return RedirectToPage("/Cart");
        }

        public IActionResult OnGetGoToCheckOut()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            foreach (var item in cartItems)
                item.CalculateTotalItemPrice();

            CartItems = _productQuery.CheckInventoryStatus(cartItems);
            if (cartItems.Any(x => !x.IsInStock))
                return RedirectToPage("/Cart");
            return RedirectToPage("/CheckOut");
        }
    }
}

ServiceHost/Pages/CheckOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using _0_Framework.Application.ZarinPal;
using _01_LampshadeQuery.Contracts;
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nancy.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages
{
    [Authorize]
    public class CheckOutModel : PageModel
    {
        public Cart Cart;
        public const string CookieName = "cart-items";
        private readonly ICartCalculatorService _calculatorService;
        private readonly ICartService _cartService;
        private readonly IProductQuery _productQuery;
        private readonly IOrderApplication _orderApplication;
        private readonly IZarinPalFactory _zarinPalFactory;
        private readonly IAuthHelper _authHelper;
        public CheckOutModel(ICartCalculatorService calculatorService, ICartService cartService, IProductQuery productQuery, IOrderApplication orderApplication, IZarinPalFactory zarinPalFactory, IAuthHelper authHelper)
        {
            Cart = new Cart();
            _calculatorService = calculatorService;
            _cartService = cartService;
            _productQuery = productQuery;
            _orderApplication = orderApplication;
            _zarinPalFactory = zarinPalFactory;
            _authHelper = authHelper;
        }

        public void OnGet()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            foreach (var item in cartItems)
                item.CalculateTotalItemPrice();

            Cart = _calculatorService.ComputeCart(cartItems);

            _cartService.Set(Cart);
        }

        public IActionResult OnPostPay(int paymentMethod)
        {
            var cart = _cartService.Get();
            cart.SetPaymentMethod(paymentMethod);
            var result = _productQuery.CheckInventoryStatus(cart.Items);

            if (result.Any(x => !x.IsInStock))
                return RedirectToPage("/Cart");

            var orderId = _orderApplication.PlaceOrder(cart);

            if (paymentMethod == 1)
            {
                var paymentResponse = _zarinPalFactory.CreatePaymentRequest(cart.PayAmount.ToString(), "", "",
                    "خرید از درگاه لوازم خانگی و دکوری", orderId);

                return Redirect($"https://{_zarinPalFactory.Prefix}.zarinpal.com/pg/StartPay/{paymentResponse.Authority}");
            }
            var paymentResult = new PaymentResult();
            return RedirectToPage("/PaymentResult", paymentResult.Succeeded("سفارش شما با موفقیت ثبت شد . پس از تماس کارشناسان ما و پرداخت وجه سفارش ارسال خواهد شد.", null));
        }

        public IActionResult OnGetCallBack([FromQuery] string authority, [FromQuery] string status, [FromQuery] long oId)
        {
            var orderAmount = _orderApplication.GetAmountBy(oId);
            var verificationResponse = _zarinPalFactory.CreateVerificationRequest(authority, orderAmount.ToString(CultureInfo.InvariantCulture));

            var result = new PaymentResult();

            if (status == "OK" && verificationResponse.Status >= 100)
            {
                var issueTrackingNo = _orderApplication.PaymentSucceeded(oId, verificationResponse.RefID);
                Response.Cookies.Delete("cart-items");
                result = result.Succeeded("پرداخت با موفقیت انجام شد.", issueTrackingNo);
                return RedirectToPage("/PaymentResult", result);
            }
            else
            {
                result = result.Failed("پرداخت ناموفق بود. در صورت کسر وجه از حساب شما، مبلغ تا ۲۴ ساعت آینده به حساب شما برگردانده میشود.");
                return RedirectToPage("/PaymentResult", result);

            }
        }
    }
}

ServiceHost/Pages/ContactUs.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BP.Presentation.Pages
{
    public class ContactUsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/ViewComponents/LatestArrivalsViewComponent.cs
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArrivalsViewComponent : ViewComponent
    {
        private readonly IProductQuery _productQuery;

        public LatestArrivalsViewComponent(IProductQuery productQuery)
        {
            _productQuery = productQuery;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productQuery.GetLatestArrivals();
            return View(products);
        }
    }
}

ServiceHost/ViewComponents/LatestArticlesViewComponent.cs
using _01_LampshadeQuery.Contracts.Article;
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArticlesViewComponent : ViewComponent
    {
        private readonly IArticleQuery _articleQuery;

        public LatestArticlesViewComponent(IArticleQuery articleQuery)
        {
            _articleQuery = articleQuery;
        }


        public IViewComponentResult Invoke()
        {
            var products = _articleQuery.LatestArticles();
            return View(products);
        }
    }
}

ServiceHost/ViewComponents/ProductCategoryViewComponent.cs
using _01_LampshadeQuery.Contracts.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class ProductCategoryViewComponent : ViewComponent
    {
        private readonly IProductCategoryQuery _productCategoryQuery;

        public ProductCategoryViewComponent(IProductCategoryQuery productCategoryQuery)
        {
            _productCategoryQuery = productCategoryQuery;
        }

        public IViewComponentResult Invoke()
        {
            var productCategories = _productCategoryQuery.GetProductCategories();
            return View(productCategories);
        }
    }
}

ServiceHost/ViewComponents/SlideViewComponent.cs
using _01_LampshadeQuery.Contracts.Slide;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class SlideViewComponent : ViewComponent
    {
        private readonly ISlideQuery _slideQuery;

        public SlideViewComponent(ISlideQuery slideQuery)
        {
            _slideQuery = slideQuery;
        }

        public IViewComponentResult Invoke()
        {
            var slides = _slideQuery.GetSlides();
            return View(slides);
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
}

<div class="wrapper-page">
    <div class="ex-page-content text-center">
        <h1>404!</h1>
        <h2>صفحه مورد نظر پیدا نشد !</h2>
        <br>
    </div>
</div>

ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}

<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود و ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                @if (Model.LoginMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.LoginMessage</div>
                                }
                                <form method="post" asp-page-handler="Login">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label>*نام کاربری</label>
                                                <input type="text" name="username" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-12">
                                                <label>رمز عبور</label>
                                                <input type="password" name="password" placeholder="رمز عبور">
                                            </div>

                                            @*<div class="col-sm-6">
                                                    <div class="check-box d-inline-block ml-0 ml-md-2">
                                                        <input type="checkbox" id="remember_me">
                                                        <label for="remember_me">Remember me</label>
                                                    </div>
                                                </div>*@

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <a href="#" class="forget-pass-link">رمز را فراموش کرده اید ؟</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                                @if (Model.RegisterMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.RegisterMessage</div>
                                }
                                <form method="post" asp-page-handler="Register">

                                    <div class="login-form">
                                        <h4 class="login-title">ثبت نام</h4>

                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کامل</label>
                                                <input type="text" name="fullName" placeholder="نام کامل">
                                            </div>
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کاربری</label>
                                                <input type="text" name="userName" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-md-12 mb-20">
                                                <label>شماره موبایل</label>
                                                <input type="number" name="mobile" placeholder="شماره موبایل">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>رمز عبور</label>
                                                <input type="password" name="password" placeholder="رمز عبور">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>تایید رمز عبور</label>
                                                <input type="password" name="rePassword" placeholder="تایید رمز عبور">
                                            </div>
                                            <div class="col-12">
                                                <button class="register-button mt-0">ثبت نام</button>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/ContactUs.cshtml
@page
@model BP.Presentation.Pages.ContactUsModel
@{
}

<div class="container">
    <main class="pb-3">
        <div class="card text-center">
            <div class="card-body">
                <i class="fa fa-phone ml-3"></i> تلفن : 09921221500
            </div>
            <div class="card-body">
                <i class="fa fa-envelope ml-3"></i> ایمیل : <a href="mailto:imrezaghiasi@gmail.com">imrezaghiasi@gmail.com</a>
            </div>
        </div>
    </main>
</div>

ServiceHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "فروشگاه نایت";
}


@await Component.InvokeAsync("Slide")
<!--====================  category area ====================-->
@await Component.InvokeAsync("ProductCategory")
<!--====================  End of category area  ====================-->
<!--====================  single row slider tab ====================-->
@await Component.InvokeAsync("ProductCategoryWithProduct")
<!--====================  End of single row slider tab  ====================-->
<!--====================  single row slider ====================-->
@await Component.InvokeAsync("LatestArrivals")
<!--====================  End of single row slider  ====================-->
<!--====================  banner hover area ====================-->
<div class="banner-hover-area section-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  banner hover wrapper  =======-->
                <div class="banner-hover-wrapper">
                    <div class="row">
                        <div class="col-md-6">
                            <!--=======  single hover banner  =======-->
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="#">
                                        <img src="~/Theme/assets/img/banners/img1-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Black Friday</h4>
                                        <h3 class="big-text">Save Up To 50% Off</h3>
                                        <a class="banner-link" asp-page="/Index">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                            <!--=======  End of single hover banner  =======-->
                        </div>

                        <div class="col-md-6">
                            <!--=======  single hover banner  =======-->
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="#">
                                        <img src="~/Theme/assets/img/banners/img2-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Best Selling !</h4>
                                        <h3 class="big-text">Living Room Up To 70% Off</h3>
                                        <a class="banner-link" asp-page="/Index">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                            <!--=======  End of single hover banner  =======-->
                        </div>
                    </div>
                </div>
                <!--=======  End of banner hover wrapper  =======-->
            </div>
        </div>
    </div>
</div>
<!--====================  End of banner hover area  ====================-->
<!--====================  feature logo area ====================-->
<div class="feature-logo-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!--=======  feature logo wrapper  =======-->
                <div class="feature-logo-wrapper section-space--inner-bottom">
                    <div class="row">
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/free_shipping.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">FREE SHIPPING WORLDWIDE</h4>
                                    <p class="short-desc">
                                        We offer free shipping via Standard Shipping on orders
                                        over $200.00
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/money_back.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">MONEY BACK GUARANTEE</h4>
                                    <p class="short-desc">
                                        If you're not satisfied with our product, we'll refund the
                                        purchase price*.
                                    </p>
                                </div>
                            </div>
                            <!--=======  End of single feature logo  =======-->
                        </div>
                        <div class="col-md-4">
                            <!--=======  single feature logo  =======-->
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/support247.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">ONLINE SUPPORT 24/7</h4>
                                    <p class="short-desc">
                                        Our friendly support team is available to help you 24
                                        hours a day, seven days a week
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("LatestArticles")