ServiceHost/Areas/Administration/Pages/Comment/Index.cshtml.cs
using System.Collections.Generic;
using CommentManagement.Application.Contracts.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Comment
{
    public class IndexModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public List<CommentViewModel> Comments { get; set; }
        private readonly ICommentApplication _commentApplication;
        public CommentSearchModel SearchModel;
        public IndexModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }


        public void OnGet(CommentSearchModel searchModel)
        {
            Comments = _commentApplication.Search(searchModel);
        }

        public IActionResult OnGetConfirm(long id)
        {
            var result = _commentApplication.Confirm(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }
        public IActionResult OnGetCancel(long id)
        {
            var result = _commentApplication.Cancel(id);
            if (result.IsSucceeded)
                return RedirectToPage("./Index");

            Message = result.Message;
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Comment/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Comment.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت کامنت ها";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["Title"]</h4>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کامنت ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Name"></label>
                        <input asp-for="SearchModel.Name" class="form-control" placeholder="نام کاربر">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Email"></label>
                        <input asp-for="SearchModel.Email" class="form-control" placeholder="ایمیل">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" >
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کامنت ها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>ایمیل</th>
                                    <th>نظر</th>
                                    <th>تاریخ</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Comments)
                                {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Name</td>
                                    <td>@item.Email</td>
                                    <td>@item.Message</td>
                                    <td>@item.CreationDate</td>
                                    <td class="text-center">
                                        @if (item.IsCanceled)
                                        {
                                            <span class="text-danger">کنسل شده</span>
                                        }
                                        @if(!item.IsCanceled && !item.IsConfirmed)
                                        {
                                            <span class="text-warning">در انتظار تایید</span>
                                        }
                                        @if(!item.IsCanceled && item.IsConfirmed)
                                         {
                                             <span class="text-success">تایید شده</span>
                                         }
                                    </td>
                                    <td>
                                        <a asp-page="./Index" asp-page-handler="Cancel" asp-route-id="@item.Id" class="btn btn-danger  waves-effect waves-light m-b-5">کنسل</a>

                                        @if (!item.IsConfirmed)
                                        {
                                            <a asp-page="./Index" asp-page-handler="Confirm" asp-route-id="@item.Id" class="btn btn-success waves-effect waves-light m-b-5">تایید</a>
                                        }

                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}